package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	gql1 "github.com/taichi-t/go_todo_v2/adapter/gql"
	model1 "github.com/taichi-t/go_todo_v2/adapter/gql/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model1.NewTodo) (*model1.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Mutation returns gql1.MutationResolver implementation.
func (r *Resolver) Mutation() gql1.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
